### ISSUE TITLE
HTML tags are escaped in mj-text

### ISSUE THREAD

**Issue by baartch** [mifi/mjml-dynamic#2]
Hey, thumbs up for this project! I like it

I have a question. Escaping UTF8 prevents HTML tags from being rendered. Is there way to go without escaping?
https://github.com/mifi/mjml-dynamic/blob/4d5896872b7c20a216a4bf497870e44f0d823592/src/index.ts#L125

If I'd like to replace the content of an element with the tag `mj-text` that contains HTML, its not rendered properly. Something like the following is not working.
```typescript
const replacers: {
  'myReplaceId': {
    content: "<p>Some text in a paragraph.</p>"
  }
}
```

Can we avoid escaping HTML tags?

**Comment by mifi** [comment]
hi. if yo uwant to avoid escaping UTF8, you can try to use a function

```js
const replacers: {
  'myReplaceId': {
    content: () => "<p>Some text in a paragraph.</p>"
  }
}

```
